### ISSUE TITLE
Error: WinAnsi cannot encode with some non-latin text dropdown value

### ISSUE THREAD

**Issue by michchan** [Hopding/pdf-lib#1152]
### Original implementation
I have a form logic that fills a dropdown with a value combining of English and Chinese character.
```javascript
const dropdownField= form.getDropdown('someDropdown');
dropdownField.select('have not 沒有');
```

### Error encountered
```
(node:65668) UnhandledPromiseRejectionWarning: Error: WinAnsi cannot encode "沒" (0x6c92)
    at Encoding.encodeUnicodeCodePoint (/User/username/project/node_modules/@pdf-lib/standard-fonts/lib/Encoding.js:23:23)
    at StandardFontEmbedder.encodeTextAsGlyphs (/User/username/project/node_modules/pdf-lib/src/core/embedders/StandardFontEmbedder.ts:124:35)
    at StandardFontEmbedder.encodeText (/User/username/project/node_modules/pdf-lib/src/core/embedders/StandardFontEmbedder.ts:50:25)
    at PDFFont.encodeText (/User/username/project/node_modules/pdf-lib/src/api/PDFFont.ts:72:26)
    at Object.exports.layoutSinglelineText (/User/username/project/node_modules/pdf-lib/src/api/text/layout.ts:324:24)
    at exports.defaultDropdownAppearanceProvider (/User/username/project/node_modules/pdf-lib/src/api/form/appearances.ts:545:30)
    at PDFDropdown.updateWidgetAppearance (/User/username/project/node_modules/pdf-lib/src/api/form/PDFDropdown.ts:649:45)
    at PDFDropdown.updateAppearances (/User/username/project/node_modules/pdf-lib/src/api/form/PDFDropdown.ts:631:12)
    at PDFDropdown.defaultUpdateAppearances (/User/username/project/node_modules/pdf-lib/src/api/form/PDFDropdown.ts:602:10)
    at PDFForm.updateFieldAppearances (/User/username/project/node_modules/pdf-lib/src/api/form/PDFForm.ts:647:15)
```

### Tried solutions

I have tried embed a custom font with Chinese character suppport:
```javascript
const fontBytes = await new Promise((resolve: (data: null | Buffer) => void) =>
  fs.readFile('public/fonts/Microsoft-JhengHei-Bold.ttf', (err, data) => {
    if (err) resolve(null);
    else resolve(data);
  }),
);
let customFont;
if (fontBytes) {
  pdfDoc.registerFontkit(fontkit);
  await pdfDoc.embedFont(fontBytes);
  customFont = await pdfDoc.embedFont(fontBytes);
}
```

Then I tried the following solutions however I got the same error:

1. Call `form.updateFieldAppearances` with custom font before calling `dropdownField.select('have not 沒有')`:
```javascript
//...
dropdownField.select('have not 沒有');
form.updateFieldAppearances(customFont);
```

2. Call `dropdownField.updateAppearances` with custom font before calling `dropdownField.select('have not 沒有')`:
```javascript
//...
const dropdownField= form.getDropdown('someDropdown');
dropdownField.updateAppearances(customFont);
dropdownField.select('have not 沒有');
```

### Additional Notes

It WORKED when I applied the following workaround:
```javascript
const rawUpdateFieldAppearances = form.updateFieldAppearances.bind(form);
form.updateFieldAppearances = function () {
   return rawUpdateFieldAppearances(customFont);
};
```

**Comment by aeharding** [comment]
Thank you for your workaround! I also had this issue with `ńñ` characters.

Using the Google Lato font:

When I simply called `form.updateFieldAppearances(latoFont)`, I got the error.

When I used your workaround, it worked great!

**Comment by cl3mcg** [comment]
Hello, thanks a lot for providing this solution.
I also recently discovered a font called [TITUS Cyberbit](https://en.wikipedia.org/wiki/Bitstream_Cyberbit) which is a pan-unicode font that supports both Latin, CKJ glyphs and many other languages.
I use this font to avoid any font/encoding issue. The font is a very traditional serif font so it might not blend in easily in your project, but it helps to solve all the encoding issues.
I thing this information can be useful to your case.
Cheers.

**Comment by glimmbo** [comment]
Also Google's [Noto Font](https://fonts.google.com/noto) covers a lot of langauges

**Comment by MuBaiDing** [comment]
thanks for your workaround,it WORKED  very well!
