### ISSUE TITLE
Cannot create textField with fontSize 

### ISSUE THREAD

**Issue by anhvt1989** [Hopding/pdf-lib#1255]
### What were you trying to do?

`var idText = makeid(16);
  const textField = form.createTextField(idText);
  textField.setText(obj.text);  
  textField.setFontSize(12);`

It happen an error : 
Uncaught (in promise) TypeError: textField.setFontSize is not a function
    at _callee18$ (init.js:2454:1)
    at tryCatch (init.js:2:1)
    at Generator._invoke (init.js:2:1)
    at Generator.next (init.js:2:1)
    at asyncGeneratorStep (init.js:3:1)
    at _next (init.js:3:1)

### How did you attempt to do it?

I need to edit a pdf file and add new textField with text and font size

### What actually happened?

I cannot add new textField with text and font size

### What did you expect to happen?

Add textField success!

### How can we reproduce the issue?

Short 

### Version

lastes

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

Thanks so much!

**Comment by tviktar** [comment]
Hi @anhvt1989, was you able to resolve it? Thanks
