### ISSUE TITLE
Could not find page for PDFRef Error during flatten

### ISSUE THREAD

**Issue by makarov-roman** [Hopding/pdf-lib#1281]
### What were you trying to do?

flatten document.

### How did you attempt to do it?

example to reproduce below
### What actually happened?

crash on flatten call
```
Error: Could not find page for PDFRef 220 0 R
    at PDFForm.findWidgetPage (/home/roman/Projects/monorepo/packages/lambdas/pdfService/node_modules/pdf-lib/cjs/api/form/PDFForm.js:603:23)
    at PDFForm.flatten (/home/roman/Projects/monorepo/packages/lambdas/pdfService/node_modules/pdf-lib/cjs/api/form/PDFForm.js:458:33)
```

### What did you expect to happen?

not having a crash

### How can we reproduce the issue?

```js
const { PDFCheckBox, PDFDocument, PDFTextField } = require('pdf-lib');
const fs = require('fs');

const fill = async () => {
  try {
    const Body = fs.readFileSync(
      'internshipApplicationForFurtherEducation.pdf',
    );

    const pdfDoc = await PDFDocument.load(Body);
    const form = pdfDoc.getForm();
    form.flatten();

    const result = await pdfDoc.save({ useObjectStreams: true });
    fs.writeFileSync('result.pdf', result);
  } catch (e) {
    console.error(e);
    throw e;
  }
};
fill();

```
[file](https://drive.google.com/file/d/1uhmiwcyESdbmuIPRLs3i6kQSGNtIJDCS/view?usp=sharing)

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

In our project I have around 30 different pdfs and only 2 has such issue. Not sure if it's corrupted metadata or something else. Before it was working with pdftk.

**Comment by makarov-roman** [comment]
I've made minor patch to ignore this error inside `flatten` and `findWidgetPage` functions and result doc look fine. So my assumption is that some editor left broken meta-data, thus pdflib "see" widget, but cannot find it on page. Ideally we should check it during `load` and clean such broken widgets/refs.
I'll publish the workaround tomorrow.

**Comment by makarov-roman** [comment]
[here is my workaround](https://github.com/Hopding/pdf-lib/commit/f7965b9f1aef688f517d38252ba6328e76b74783)
you can test it via `@visaright/pdf-lib` npm package. (you can use package with caution, cause it will be removed after the issue is properly fixed in the mainstream)
