### ISSUE TITLE
Flattening IRS Form W-8BEN throws `Error: Unexpected N type: undefined`

### ISSUE THREAD

**Issue by richmoni** [Hopding/pdf-lib#1347]
### What were you trying to do?

Hello, I am attempting flatten an IRS [Form W-8 BEN (Rev. October 2021)](https://www.irs.gov/pub/irs-pdf/fw8ben.pdf), but doing so causes an `UnhandledPromiseRejectionWarning: Error: Unexpected N type: undefined` error to be thrown.

Please let me know of any workaround for this issue or if a fix can be implemented. Thanks!

### How did you attempt to do it?

This bug can be reproduced by simply loading the form and calling `form.flatten()` as follows:
```
import { readFileSync } from 'fs';
import { resolve } from 'path';

const PDF_PATH = resolve('file/path/here', 'fw8ben.pdf');

async function main() {
  const pdfDoc = await PDFDocument.load(readFileSync(PDF_PATH));
  const form = pdfDoc.getForm();

  form.flatten();  // <-- error thrown here
}

void main();
```

### What actually happened?

The following error is thrown:
```
(node:59600) UnhandledPromiseRejectionWarning: Error: Unexpected N type: undefined
    at PDFWidgetAnnotation.PDFAnnotation.getNormalAppearance (/Users/foo/bar/baz/packages/library/node_modules/pdf-lib/src/core/annotation/PDFAnnotation.ts:70:11)
    at PDFForm.findWidgetAppearanceRef (/Users/foo/bar/baz/packages/library/node_modules/pdf-lib/src/api/form/PDFForm.ts:724:28)
    at PDFForm.flatten (/Users/foo/bar/baz/packages/library/node_modules/pdf-lib/src/api/form/PDFForm.ts:551:32)
    at <local code>
```

### What did you expect to happen?

I expect no errors to be thrown and for the form to be successfully flattened.

### How can we reproduce the issue?

Running the above code snippet will reproduce the issue.

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by masotrix** [comment]
What worked for me was to delete each field iteratively using this https://github.com/Hopding/pdf-lib/issues/1168#issuecomment-1321581900
