### ISSUE TITLE
Loading particular pdf crashes pdf-lib

### ISSUE THREAD

**Issue by Leone25** [Hopding/pdf-lib#1408]
### What were you trying to do?

Loading [this pdf](https://mega.nz/file/lkRCGQRJ#An4nH8Iaw2PP4TUF6dXqWVpAGmLYva-83WlAwNmis7Q) crashes pdf-lib

### How did you attempt to do it?

```js
const page = await PDFDocument.load(pdfData);
```

### What actually happened?

error:

```
_this.catalog.Pages().traverse(function (node, ref) {
                          ^

TypeError: _this.catalog.Pages is not a function
    at PDFDocument.computePages [as populate] (C:\Users\user\bSmart-downloader\node_modules\pdf-lib\cjs\api\PDFDocument.js:28:27)
    at Cache.access (C:\Users\user\bSmart-downloader\node_modules\pdf-lib\cjs\utils\Cache.js:13:31)
    at PDFDocument.getPages (C:\Users\user\bSmart-downloader\node_modules\pdf-lib\cjs\api\PDFDocument.js:479:31)
    at PDFDocument.<anonymous> (C:\Users\user\bSmart-downloader\node_modules\pdf-lib\cjs\api\PDFDocument.js:648:43)
    at step (C:\Users\user\bSmart-downloader\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\user\bSmart-downloader\node_modules\tslib\tslib.js:122:57)
    at fulfilled (C:\Users\user\bSmart-downloader\node_modules\tslib\tslib.js:112:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.10.0
```

### What did you expect to happen?

To load the pdf

### How can we reproduce the issue?

Easy way to reproduce the issue is to just open https://pdflabeler.enrico.wtf/ , open the console, and try to pen the pdf i linked to

### Version

1.17.0 (i tried older ones, they have the same issue)

### What environment are you running pdf-lib in?

Browser, Node

**Comment by harshajayaweeraXHJ** [comment]
Any update on this. Having the same issue

**Comment by Leone25** [comment]
Not that i know of, unfortunately hopding doesn't have much time that they can dedicate to maintain this library
