### ISSUE TITLE
PDFDocument.save() generates pdf missing trailer dictionary

### ISSUE THREAD

**Issue by cory-zpaper** [Hopding/pdf-lib#1410]
### What were you trying to do?

I am generating a file input part of a multipart form via PDFDocument.save() (adding the part via FormData.append()). On the server, I'm trying to open the received pdf file with pdfBox. I'm getting the following error.
`Caused by: java.io.IOException: Missing root object specification in trailer.
        at org.apache.pdfbox.pdfparser.COSParser.parseTrailerValuesDynamically(COSParser.java:2947) ~[pdfbox-2.0.26.jar:2.0.26]
`

The exception says that the specification is missing in the trailer but when I look at the data that was uploaded, the trailer is completely missing.

Is there some parameter that I can send to save() to make sure the trailer dictionary is produced?

### How did you attempt to do it?

I created browser-side javascript that is saving the pdf content (via PDFDocument.save()) to an array that is being posted to a server as part of a multipart form.

### What actually happened?

In my server code, when I try to read the posted pdf document, pdfBox gives me this exception:
`Caused by: java.io.IOException: Missing root object specification in trailer.
        at org.apache.pdfbox.pdfparser.COSParser.parseTrailerValuesDynamically(COSParser.java:2947) ~[pdfbox-2.0.26.jar:2.0.26]
`

### What did you expect to happen?

I expected pdfBox to be able to open the document.

### How can we reproduce the issue?

The code is not short to do this, since an ajax call is being made that is posting a multipart form. I'm hoping that the problem can be duplicated without looking at my code, but if code is required, I can work up a smaller bit of code that demonstrates the problem.

### Version

1.17.1

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by cory-zpaper** [comment]
Please note that while pdfBox complains about a root object specification missing from trailer, actually the entire trailer is missing.

**Comment by rbonestell** [comment]
This is still a problem today, I discovered when attempting to apply a digital signature to a PDF which I had modified using `pdf-lib` and the `trailer` was missing from the resulting PDF.

**Comment by tref01l-pr** [comment]
> This is still a problem today, I discovered when attempting to apply a digital signature to a PDF which I had modified using `pdf-lib` and the `trailer` was missing from the resulting PDF.

Please tell me what you are using, if you have in pdf file when processing pdf file in this way Loader.loadPDF(workingFile); the following error 2025-01-24 19:25:48 WARN o.apache.pdfbox.pdfparser.PDFParser Error: Header doesn't contain versioninfo
It only happens to one file, but I can open it to view it, so I don't understand why it is considered corrupted

[GrundrisszurBearbeitung191691.pdf](https://github.com/user-attachments/files/18540265/GrundrisszurBearbeitung191691.pdf)
