### ISSUE TITLE
Cannot make "setKeywords" work.

### ISSUE THREAD

**Issue by bwims** [Hopding/pdf-lib#1426]
### What were you trying to do?

I was trying to change the metadata in a pdf.  I successfully changed Title, Author, and Subject. 
Keywords kept crashing the environment with errors suspiciously like a bug.

### How did you attempt to do it?

I am using a low code environment called Node-Red, based on Node.js

Data is transmitted as message blocks which are processed by nodes, one of which can be a JS function node.

The function node allows me to import pdf-lib in its setup:
![image](https://user-images.githubusercontent.com/18516073/229289349-eb77e4c7-fced-40a2-86a2-f5eba28a156e.png)

As part of my test, I read a pdf as a single buffer object and send it to the function as msg.payload. 

The function is based on one of your examples with the removal of the fetch routine, and is as follows:

```
var existingPdfBytes =[]
existingPdfBytes = msg.payload

readDocumentMetadata()
return msg;
async function readDocumentMetadata() {

    const pdfDoc = await pdfLib.PDFDocument.load(existingPdfBytes, {
        updateMetadata: true
    })
    
    console.log('Title:', pdfDoc.getTitle())
    console.log('Author:', pdfDoc.getAuthor())
    console.log('Subject:', pdfDoc.getSubject())
    console.log('Creator:', pdfDoc.getCreator())
    console.log('Keywords:', pdfDoc.getKeywords())
    console.log('Producer:', pdfDoc.getProducer())
    console.log('Creation Date:', pdfDoc.getCreationDate())
    console.log('Modification Date:', pdfDoc.getModificationDate())
}

```
I hand edited the document fields of a pdf, and the output is as follows:
```
Title: test1
Author: test2
Subject: test3
Creator:
Keywords: "hobbies, makers, electronics"
Producer:
Creation Date: 2022-11-05T06:47:48.000Z
Modification Date: 2023-04-01T12:50:36.000Z
```
Note the keywords content.

Next, I modified the routine to include some set commands; the following works:
(note that setKeywords is commented out)
```
async function readDocumentMetadata(keywords) {

    const pdfDoc = await pdfLib.PDFDocument.load(existingPdfBytes, {
        updateMetadata: true
    })
    pdfDoc.setTitle('Practical Electronics')
    pdfDoc.setAuthor('Mike Kenward')
    pdfDoc.setSubject('Electronics')
    //pdfDoc.setKeywords(["hobbies", "makers", "electronics"])

    keywords = pdfDoc.getKeywords()
    node.warn(keywords)
    const pdfBytes = await pdfDoc.save()
    
    console.log('Title:', pdfDoc.getTitle())
    console.log('Author:', pdfDoc.getAuthor())
    console.log('Subject:', pdfDoc.getSubject())
    console.log('Creator:', pdfDoc.getCreator())
    console.log('Keywords:', pdfDoc.getKeywords())
    console.log('Producer:', pdfDoc.getProducer())
    console.log('Creation Date:', pdfDoc.getCreationDate())
    console.log('Modification Date:', pdfDoc.getModificationDate())
}
```

The output looks fine.  (for some reason, the creator and producer fields have been updated too - pdfDoc.save?)

```
Title: Practical Electronics
Author: Mike Kenward
Subject: Electronics
Creator: pdf-lib (https://github.com/Hopding/pdf-lib)
Keywords: "hobbies, makers, electronics"
Producer: pdf-lib (https://github.com/Hopding/pdf-lib)
Creation Date: 2022-11-05T06:47:48.000Z
Modification Date: 2023-04-01T12:59:50.000Z
```

### What actually happened?

When the line 

`pdfDoc.setKeywords(["hobbies", "makers", "electronics"])`

is uncommented, this is the result:

```
1 Apr 14:08:04 - [red] Uncaught Exception:
1 Apr 14:08:04 - [error] TypeError: `keywords` must be of type `Array`, but was actually of type `NaN`
    at Object.exports.assertIs (C:\Users\williams_b\.node-red\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at PDFDocument.setKeywords (C:\Users\williams_b\.node-red\node_modules\pdf-lib\cjs\api\PDFDocument.js:382:17)
    at readDocumentMetadata (Function node:4bfcc30399b5a64e [function 17]:17:12)


```

If I provide an empty array, It produces this curious error:

```
1 Apr 14:09:55 - [red] Uncaught Exception:
1 Apr 14:09:55 - [error] TypeError: `keywords` must be of type `Array`, but was actually of type `Array`
    at Object.exports.assertIs (C:\Users\williams_b\.node-red\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at PDFDocument.setKeywords (C:\Users\williams_b\.node-red\node_modules\pdf-lib\cjs\api\PDFDocument.js:382:17)
    at readDocumentMetadata (Function node:4bfcc30399b5a64e [function 17]:17:12)

```

Finally, I used a  new Array declaration as follows
`    const keywords = new Array('hobbies', 'makers', 'electronics')`
but got the same NaN error...

```
1 Apr 14:22:57 - [red] Uncaught Exception:
1 Apr 14:22:57 - [error] TypeError: `keywords` must be of type `Array`, but was actually of type `NaN`
    at Object.exports.assertIs (C:\Users\williams_b\.node-red\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at PDFDocument.setKeywords (C:\Users\williams_b\.node-red\node_modules\pdf-lib\cjs\api\PDFDocument.js:382:17)
    at readDocumentMetadata (Function node:4bfcc30399b5a64e [function 17]:18:12)

```

### What did you expect to happen?

I simply expected the setKeywords routine to work as described.

### How can we reproduce the issue?

There is no need to share any PDF, because all the code is doing is change metadata, so should "work" on any sample PDF

Here is the failing piece of code.  Unless you run Node-Red, I'm not sure how to send you a working example, as I don't have any other environment, but since most of it is based on your examples, it would probably be easier for you to cut and paste?

Let me know what else you need.

```
var existingPdfBytes =[]

existingPdfBytes = msg.payload

readDocumentMetadata()

return msg;
async function readDocumentMetadata() {
    const keywords = new Array('hobbies', 'makers', 'electronics')
    const pdfDoc = await pdfLib.PDFDocument.load(existingPdfBytes, {
        updateMetadata: true
    })
    pdfDoc.setTitle('Practical Electronics')
    pdfDoc.setAuthor('Mike Kenward')
    pdfDoc.setSubject('Electronics')

    pdfDoc.setKeywords(keywords)


    const pdfBytes = await pdfDoc.save()
    
    console.log('Title:', pdfDoc.getTitle())
    console.log('Author:', pdfDoc.getAuthor())
    console.log('Subject:', pdfDoc.getSubject())
    console.log('Creator:', pdfDoc.getCreator())
    console.log('Keywords:', pdfDoc.getKeywords())
    console.log('Producer:', pdfDoc.getProducer())
    console.log('Creation Date:', pdfDoc.getCreationDate())
    console.log('Modification Date:', pdfDoc.getModificationDate())
}

```

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by bwims** [comment]
Well this is depressing.  I was hoping it would be something simple.
