### ISSUE TITLE
addEventListener does not work on PDFLib objects 

### ISSUE THREAD

**Issue by gintares** [Hopding/pdf-lib#1456]
### What were you trying to do?

addEventListeners 'click', 'onclick' to various PDFLib objects .

I was not progrmming for last two years, i am not sure if prototype supports addEventListener. But , as far as i remember all objects i was creating and using on 2017-2020 were supporting EventListeners. 

It looks like deliberate efforts to remove the main javascript language property, because javascript is about user-mouse interaction with web-page.

### How did you attempt to do it?

    firstPage.addEventListener('onclick', (e) => { const windowCoordinates = getMouseLocation(e); });
//Uncaught (in promise) TypeError: firstPage.addEventListener is not a function at gloadPdf (ex3a.js:145:15)
    
    
    pdfDoc.addEventListener('onclick', (e) => { const windowCoordinates = getMouseLocation(e);    });
    //ex3a.js:146 Uncaught (in promise) TypeError: pdfDoc.addEventListener is not a function at gloadPdf (ex3a.js:146:12)
    
    pdfDoc.prototype.addEventListener('onclick', (e) => {  const windowCoordinates = getMouseLocation(e);   });
    //uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener') at gloadPdf (ex3a.js:150:22)
    
    viewerPrefs.addEventListener('onclick', (e) => {  const windowCoordinates = getMouseLocation(e);   });
//Uncaught (in promise) TypeError: viewerPrefs.addEventListener is not a function  at gloadPdf (ex3a.js:153:17)
    
    
    viewerPrefs.prototype.addEventListener('onclick', (e) = {  const windowCoordinates = getMouseLocation(e);  });
    //Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')at gloadPdf (ex3a.js:157:27)

### What actually happened?

addEventListener method does not work

### What did you expect to happen?

to get mouse coordinates in window when clicking on PDFLib object

### How can we reproduce the issue?

function getMouseLocation(e) {
  //const scrollElement = docView.getScrollViewElement();
  const scrollLeft = 0; //scrollElement.scrollLeft || 0;
  const scrollTop = 0; //scrollElement.scrollTop || 0;
  console.log('e.pageX='+e.pageX+'  e.pageY='+e.pageY); 
  return {
    x: e.pageX + scrollLeft,
    y: e.pageY + scrollTop
  };
};

const fileSelector = document.getElementById('file-selector'); 

let fileHandle;
fileSelector.addEventListener( 'click', async () => {

    [fileHandle] = await window.showOpenFilePicker();
    console.log(fileHandle);  
const file = await fileHandle.getFile(); // returns a File object, which contains a blob. To get the data from the blob, call one of its methods, (slice(), stream(), text(), or arrayBuffer()).
    
    const ftps = fileHandle.type ? fileHandle.type : 'NOT SUPPORTED';
    console.log(ftps);

    const contents = await file.arrayBuffer(); 
    gloadPdf(contents);
}

async function gloadPdf(datapdf) {  
    
    const pdfDoc = await PDFLib.PDFDocument.create();
    const srcDoc = await PDFLib.PDFDocument.load(datapdf); 
    const copiedPages = await pdfDoc.copyPages(srcDoc, [0,3]);
    const [firstPage, fourthPage] = copiedPages;
    pdfDoc.addPage(fourthPage); 
    pdfDoc.addPage(firstPage); 
    const viewerPrefs = pdfDoc.catalog.getOrCreateViewerPreferences(); 

 
    firstPage.addEventListener('onclick', (e) => { const windowCoordinates = getMouseLocation(e); });
//Uncaught (in promise) TypeError: firstPage.addEventListener is not a function at gloadPdf (ex3a.js:145:15)
    
    
    pdfDoc.addEventListener('onclick', (e) => { const windowCoordinates = getMouseLocation(e);    });
    //ex3a.js:146 Uncaught (in promise) TypeError: pdfDoc.addEventListener is not a function at gloadPdf (ex3a.js:146:12)
    
    pdfDoc.prototype.addEventListener('onclick', (e) => {  const windowCoordinates = getMouseLocation(e);   });
    //uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener') at gloadPdf (ex3a.js:150:22)
    
    viewerPrefs.addEventListener('onclick', (e) => {  const windowCoordinates = getMouseLocation(e);   });
//Uncaught (in promise) TypeError: viewerPrefs.addEventListener is not a function  at gloadPdf (ex3a.js:153:17)
    
    
    viewerPrefs.prototype.addEventListener('onclick', (e) = {  const windowCoordinates = getMouseLocation(e);  });
    //Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')at gloadPdf (ex3a.js:157:27)

    const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
    document.getElementById('pdf').src = pdfDataUri;

}

### Version

2.0

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

I was not progrmming for last two years, i am not sure if prototype supports addEventListener. But , as far as i remember all objects i was creating and using on 2017-2020 were supporting EventListeners. 

It looks like deliberate efforts to remove the main javascript language property, because javascript is about user-mouse interaction with web-page.

**Comment by gintares** [comment]
//Conclusions, I believe there must be some events exposed to user, and some used by PDFLIb. Like 'mousedown' for user; and 'mouseup' or 'click' for PDFLib or viseversa

I tried to add event listeners on iframe and textArea.
This works:
```
var vwProt = function (gO) {
    this.docVW = document.getElementById('pdf');  
    console.log(this.docVW);  
    //this.docVW.addEventListener('click', this, false); 
   this.docVW.contentDocument.body.addEventListener('click', this, false);  
    
    this.txtVW = document.getElementById('file_area');
    console.log(this.txtVW);
    this.txtVW.addEventListener('click', this, false);   
}  // vwProt = function(gO  

vwProt.prototype.handleEvent = function(evt) {
    console.log('evt');
    console.log(evt);      
}  

var vw = new vwProt([]);
//clicking on iframe and on textarea produces events with window coordinates
```
<...>

//after inserting pdfDoc to window elements, window does not detect click events anymore. 
```
    const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
    document.getElementById('file_area').value = pdfDataUri;
    document.getElementById('pdf').src = pdfDataUri;
//clicking on iframe does no produce events in log anymore 
```

//Conclusions, I believe there must be some events exposed to user, and some used by PDFLIb. Like 'mousedown' for user; and 'mouseup' or 'click' for PDFLib or viseversa

**Comment by gintares** [comment]
I am sorry, seems it is not a bug. Seems, only window objects has EventListeners, like div element.
But, it is difficult to implement events on iframe elements.
It is not a bug, it is iframe specifics.

Final solution was to wrap iframe to div, and add one more transparent div on which click events are working.

```
<style>
    div#wrap {
        position: relative; 
    }
    div#pdfDiv {
        position:absolute; 
        top:0; left:0; width:8.3in; height:11.7in; 
        z-index: 100; 
        background: #FF7A59; opacity: 0.2;
    }
    iframe#pdf{ 
        position:absolute; 
        top:0; left:0; width:8.3in; height:11.7in;
         z-index: 99; 
    }
    #divCheck:checked + div#wrap div#pdfDiv {
        z-index: 98; 
        background: #FF7A59; opacity: 0.01;
    }
    #divCheck:not(:checked) + div#wrap div#pdfDiv {
        z-index: 100; 
        background: #FF7A59; opacity: 0.5;
    }
</style>
```

//body
```
 <input type="file" id="file-selector" >
  <label for="divCheck" id="pos_label">position</label>
    <input type="checkbox" id="divCheck" > 
    
   <div id="wrap"> 
       <div id="pdfDiv"></div>
       <iframe id="pdf" ></iframe>  
    </div>
```

//javascript 
```
var vwProt = function(gO) {  
    
    this.divVW = document.getElementById('pdfDiv');  
    console.log(this.divVW);  
    this.divVW.addEventListener('onclick', this, false);   
    this.divVW.addEventListener('click', this, false); 
    this.divVW.addEventListener('mousedown', this, false);   
}  // vwProt = function(gO    

vwProt.prototype.handleEvent = function(evt) { 
    console.log('evt.type='+evt.type+'  evt.id='+evt.target.id);  
    //console.log('evt');  
    console.log(evt);       
}  

var vw = new vwProt([]); 

const fileSelector = document.getElementById('file-selector'); 
let fileHandle;
fileSelector.addEventListener( 'click', async () => {
    [fileHandle] = await window.showOpenFilePicker();
    const file = await fileHandle.getFile(); 
    const contents = await file.arrayBuffer(); 
    gloadPdf(contents);      
} ); 

async function gloadPdf(datapdf) {  
    
    const pdfDoc = await PDFLib.PDFDocument.create();
    const srcDoc = await PDFLib.PDFDocument.load(datapdf); 
    const copiedPages = await pdfDoc.copyPages(srcDoc, [0,3]);
    const [firstPage, fourthPage] = copiedPages;
    pdfDoc.addPage(fourthPage); 
    pdfDoc.addPage(firstPage); 
    const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
    
    document.getElementById('file_area').value = pdfDataUri;
}
```
