### ISSUE TITLE
Invalid typed array length: 5310707417

### ISSUE THREAD

**Issue by surendrakanigiri24** [Hopding/pdf-lib#1461]
### What were you trying to do?

I am trying to do generate a new pdf with selective pages after drawing text boxes on them. It's working fine for fewer pages but if the count is like 100,150..... getting an invalid typed array length.

### How did you attempt to do it?

`const { PDFDocument, rgb } = require("pdf-lib");
 const geometrywithPages = {};
 const s3Data = await s3Fun(fileName, company_name.account_name);                      
 const pdfDoc = await PDFDocument.load(s3Data.buffer, { ignoreEncryption: true });
 const mergedPdf = await PDFDocument.create();
 const docPages = pdfDoc.getPages();

for (const item of geometry.rows) {
    const page = item.page;
    pages.push(page);

    if (!geometrywithPages[page]) {
      geometrywithPages[page] = [];
    }
    geometrywithPages[page].push(item);
}

pages = [...new Set(pages)];
for (const page of pages) {
    const pageGeometry = geometrywithPages[page];
    const rotation = await getPageRotation(page, s3Data.buffer);
    console.log(rotation, 'rotation');
    const firstPage = docPages[page - 1];

  for (const item of pageGeometry) {
      const geometry=JSON.parse(JSON.stringify(eval("("+item.geometry+")")));
      const { B_W, B_H, B_L, B_T } = await machSearchManager.machPageHighlationGeometry(rotation, geometry);
      const { width, height } = firstPage.getSize();

      firstPage.drawRectangle({
          x: B_L * width,
          y: (height - B_T * height) - (B_H * height),
          width: B_W * width,
          height: B_H * height,
          borderColor: rgb(1, 0, 0),
          borderWidth: 1.5
      });

      }
      const newPdf=await mergedPdf.copyPages(pdfDoc, pdfDoc.getPageIndices());
      await mergedPdf.addPage(newPdf[page-1]);
  }
console.log(await mergedPdf.save());   //It's getting error at this line
resultedFileBuffer = await fileSystem.uint8ArrayToBuffer(await mergedPdf.save());   
await fileSystem.writingPdfStream(filePath, await mergedPdf.save());
`

### What actually happened?

Getting an Invalid typed array length: 5310707417

### What did you expect to happen?

I want to generate a new pdf.

### How can we reproduce the issue?

Any pdf with 100 Pages

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

Any pdf with more than 100 pages

**Comment by surendrakanigiri24** [comment]
[error] Error at singleFileMachSearch API Invalid typed array length: 5310743764 
{
  stack: 'RangeError: Invalid typed array length: 5310743764\n' +
    '    at new Uint8Array (<anonymous>)\n' +
    '    at PDFStreamWriter.<anonymous> (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/cjs/core/writers/PDFWriter.js:31:34)\n' +
    '    at step (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/node_modules/tslib/tslib.js:141:27)\n' +
    '    at Object.next (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/node_modules/tslib/tslib.js:122:57)\n' +
    '    at fulfilled (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/node_modules/tslib/tslib.js:112:62)'
}

**Comment by RobynLuo520** [comment]
@surendrakanigiri24 Hey, bro, what's the status of this question now?
