### ISSUE TITLE
TypeError: _this.catalog.Pages(...).traverse is not a function

### ISSUE THREAD

**Issue by surendrakanigiri24** [Hopding/pdf-lib#1462]
### What were you trying to do?

`          const PDFMerger = require("pdf-merger-js");
           var merger = new PDFMerger();
            for (let j=0; j<data.length; j++) {
                console.log(data[j].url_path,'data[j].url_path')
                const doc=await PDFNet.PDFDoc.createFromURL(data[j].url_path);
                const pageCount=await doc.getPageCount();
                page_sum=page_sum+pageCount;
                console.log(page_sum)
                pageCounts.push(page_sum) // pushing each pdf total page count
                const buf=await doc.saveMemoryBuffer(
                    PDFNet.SDFDoc.SaveOptions.e_linearized
                );
                const blob=new Blob([buf], {type: "application/pdf"});
                await merger.add(await blob.arrayBuffer()); //Getting error at this line
            }`

### How did you attempt to do it?

As above

### What actually happened?

TypeError: _this.catalog.Pages(...).traverse is not a function
    at Cache.PDFDocument.computePages [as populate] (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/cjs/api/PDFDocument.js:29:35)
    at Cache.access (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/cjs/utils/Cache.js:13:31)
    at PDFDocument.getPages (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/cjs/api/PDFDocument.js:481:31)
    at PDFDocument.getPageCount (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/cjs/api/PDFDocument.js:465:35)
    at PDFDocument.getPageIndices (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-lib/cjs/api/PDFDocument.js:513:38)
    at PDFMerger._addEntireDocument (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-merger-js/index.js:56:65)
    at async PDFMerger.add (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/node_modules/pdf-merger-js/index.js:17:7)
    at async main (/opt/lampp/htdocs/bitbucketworkspace/bluetail-nodeupgradation/backend/src/controller/conformity.js:813:17)

### What did you expect to happen?

need to create an pdf

### How can we reproduce the issue?

By using above code

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

While executing the above code snippet getting an error.

**Comment by surendrakanigiri24** [comment]
It's a PDF issue. So, closing it.

**Comment by ebert-c** [comment]
> It's a PDF issue. So, closing it.

Hey I've run into a similar issue, what was the problem with the PDF? My PDF isn't being recognized as a form and I was wondering what it is that I built incorrectly.
