### ISSUE TITLE
Trying to parse invalid object while using drawRectangle

### ISSUE THREAD

**Issue by bykof** [Hopding/pdf-lib#1572]
### What were you trying to do?

I tried to add a rectangle to a page

### How did you attempt to do it?

```
page.drawRectangle({
    x: xBox,
    y: yBox,
    width: boxWidth,
    height: boxHeight,
    opacity: marker_opacity,
    color: color,
  });
```

### What actually happened?

```
   WARN  Trying to parse invalid object: {\"line\":78,\"column\":6,\"offset\":1749}).  
   WARN  Invalid object ref: 8 0 R.  
   WARN  pdf_tool/node_modules/.pnpm/pdf-lib@1.17.1/node_modules/pdf-lib/cjs/core/structures/PDFPageLeaf.js:75.  
   WARN  Contents.push(contentStreamRef);.  
   WARN  ^.  
   WARN  TypeError: Contents.push is not a function.  
   WARN  at PDFPageLeaf.addContentStream (pdf_tool/node_modules/.pnpm/pdf-lib@1.17.1/node_modules/pdf-lib/cjs/core/structures/PDFPageLeaf.js:75:18).  
   WARN  at PDFPage.getContentStream (pdf_tool/node_modules/.pnpm/pdf-lib@1.17.1/node_modules/pdf-lib/cjs/api/PDFPage.js:1365:19).  
   WARN  at PDFPage.drawRectangle (pdf_tool/node_modules/.pnpm/pdf-lib@1.17.1/node_modules/pdf-lib/cjs/api/PDFPage.js:1204:34).  
   WARN  at drawPosition (pdf_tool/index.js:96:8).   
```

### What did you expect to happen?

That the tool is able to add a rectangle

### How can we reproduce the issue?

Unfortunately I am not allowed to share the PDF with you.

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by whchi** [comment]
For anyone who facing this, here are 2 workarounds

1. Skip pages that are not normalized

This method checks if a PDF page is normalized. If it’s not, it skips drawing shapes on that page. 
**Problem**: Some pages might not show any shapes.

```js
        const normalized = page.node.normalizedEntries();
        if (normalized.Contents?.get(0)) {
          page. drawRectangle({
            x: xBox,
            y: yBox,
            width: boxWidth,
            height: boxHeight,
            opacity: marker_opacity,
            color: color,
          });
        }
```

2. Convert contents into an array

This method changes the PDF page’s contents into an array to allow drawing shapes. 
**Problem**: Shapes may not align properly with other pages.

```js
        const { context } = page.doc;
        const pageRef = page.ref;
        const pageDict = context.lookup(pageRef) as PDFDictType;

        const contents = pageDict.get(PDFName.of('Contents'));
        const actualContents = context.lookup(contents);

        if (actualContents && !(actualContents instanceof PDFArray)) {
          const newArray = context.obj([contents]);
          pageDict.set(PDFName.of('Contents'), newArray);
        }

        page. drawRectangle({
          x: xBox,
          y: yBox,
          width: boxWidth,
          height: boxHeight,
          opacity: marker_opacity,
          color: color,
        });
```

It depends on your business needs and how you discuss with clients.
