### ISSUE TITLE
Error: Invalid Stream!

### ISSUE THREAD

**Issue by mealCode** [Hopding/pdf-lib#221]
I using this library to extract images from pdf. It seems to work with some PDF but not all. I got this error:

019-10-17T16:35:38.507999+00:00 app[web.1]: /app/node_modules/pdf-lib/lib/core/pdf-parser/PDFParser.js:43
2019-10-17T16:35:38.508023+00:00 app[web.1]:                 throw e;
2019-10-17T16:35:38.508025+00:00 app[web.1]:                 ^
2019-10-17T16:35:38.508027+00:00 app[web.1]: 
2019-10-17T16:35:38.508029+00:00 app[web.1]: Error: Invalid Stream!
2019-10-17T16:35:38.508032+00:00 app[web.1]:     at parseStream (/app/node_modules/pdf-lib/lib/core/pdf-parser/parseStream.js:67:15)
2019-10-17T16:35:38.508034+00:00 app[web.1]:     at Object.exports.default (/app/node_modules/pdf-lib/lib/core/pdf-parser/parseStream.js:108:15)
2019-10-17T16:35:38.508036+00:00 app[web.1]:     at Object.parseDictOrStream [as default] (/app/node_modules/pdf-lib/lib/core/pdf-parser/parseDictOrStream.js:28:44)
2019-10-17T16:35:38.508038+00:00 app[web.1]:     at Object.parseIndirectObj [as default] (/app/node_modules/pdf-lib/lib/core/pdf-parser/parseIndirectObj.js:42:41)
2019-10-17T16:35:38.508041+00:00 app[web.1]:     at parseBodySection (/app/node_modules/pdf-lib/lib/core/pdf-parser/parseDocument.js:24:48)
2019-10-17T16:35:38.508043+00:00 app[web.1]:     at Object.parseDocument [as default] (/app/node_modules/pdf-lib/lib/core/pdf-parser/parseDocument.js:76:21)
2019-10-17T16:35:38.508044+00:00 app[web.1]:     at PDFParser.parse (/app/node_modules/pdf-lib/lib/core/pdf-parser/PDFParser.js:38:40)
2019-10-17T16:35:38.508047+00:00 app[web.1]:     at Function.PDFDocumentFactory.load (/app/node_modules/pdf-lib/lib/core/pdf-document/PDFDocumentFactory.js:45:35)

**Comment by Hopding** [comment]
Hello @mealCode! What version of pdf-lib are you using?

**Comment by mealCode** [comment]
wow, thanks a lot for fast support @Hopding - I actually find the solution:

https://github.com/Hopding/pdf-lib/issues/70

issue is fixed. Hats off

**Comment by mealCode** [comment]
@Hopding Thanks for your support.

I am pdf-lib version  "pdf-lib": "^0.6.1-rc4" which fixed Error: Invalid Stream! in development. Unfrotunately, issue persists in production. I send you the email at (andrew.dillon.j@gmail.com). with subject Error: Invalid Stream!.

Thanks for checking :)

**Comment by Hopding** [comment]
@mealCode The latest version of pdf-lib is [`v1.2.0`](https://www.npmjs.com/package/pdf-lib/v/1.2.0). Can you try out this version and see if the problem persists?

**Comment by mealCode** [comment]
version v1.2.0 causes another issue. It was my bad actually, sorry about that. I manage it to work with 0.6.1-rc4. Thanks again for your fast support :)
