### ISSUE TITLE
Cannot read property 'sizeInBytes' of undefined"

### ISSUE THREAD

**Issue by Werewolve** [Hopding/pdf-lib#481]
I try to fill some fields in an pdf file. For that I collected some helper methods from different discussions here on github. In detail I try to fill a multiline field and added some functions for that. 
If I run the code and try to fill the file I get the error "Cannot read property 'sizeInBytes' of undefined"

`	
TypeError: Cannot read property 'sizeInBytes' of undefined
    at PDFContentStream.getUnencodedContentsSize (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/structures/PDFContentStream.js:49:41)
    at PDFContentStream.getUnencodedContents (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/structures/PDFContentStream.js:38:42)
    at Cache.PDFFlateStream._this.computeContents [as populate] (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/structures/PDFFlateStream.js:14:43)
    at Cache.access (/home/node/backend_dev/node_modules/pdf-lib/cjs/utils/Cache.js:10:31)
    at PDFContentStream.PDFFlateStream.getContentsSize (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/structures/PDFFlateStream.js:27:35)
    at PDFContentStream.PDFStream.updateDict (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/objects/PDFStream.js:29:33)
    at PDFContentStream.PDFStream.sizeInBytes (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/objects/PDFStream.js:33:14)
    at PDFStreamWriter.PDFWriter.computeIndirectObjectSize (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/writers/PDFWriter.js:88:33)
    at PDFStreamWriter.<anonymous> (/home/node/backend_dev/node_modules/pdf-lib/cjs/core/writers/PDFStreamWriter.js:50:38)
    at step (/home/node/backend_dev/node_modules/pdf-lib/node_modules/tslib/tslib.js:141:27)`

This is my helper class:

```
/* eslint-disable no-await-in-loop */
/** PDF helper function module
 * @module pdfhelper
 */

'use strict';

const { PDFName, PDFNumber, breakTextIntoLines, PDFOperator, PDFHexString, PDFContentStream, PDFArray, PDFOperatorNames: Ops, asPDFName, pushGraphicsState, popGraphicsState, drawLinesOfText, degrees, rgb } = require('pdf-lib');

const pdfhelper = {

    getAcroForm: function (pdfDoc) {
        return pdfDoc.context.lookup(pdfDoc.catalog.get(PDFName.of('AcroForm')));
    },

    getAcroFields: function (pdfDoc) {
        if (!pdfDoc.catalog.get(PDFName.of('AcroForm'))) { return []; }
        const acroForm = pdfDoc.context.lookup(pdfDoc.catalog.get(PDFName.of('AcroForm')));
        if (!acroForm.get(PDFName.of('Fields'))) { return []; }
        const acroFields = acroForm.context.lookup(acroForm.get(PDFName.of('Fields')));
        return acroFields.array.map(ref => acroForm.context.lookup(ref));
    },

    findAcroFieldByName: function (pdfDoc, name) {
        const acroFields = this.getAcroFields(pdfDoc);
        return acroFields.find((acroField) => {
            const fieldName = acroField.get(PDFName.of('T'));
            return !!fieldName && fieldName.value === name;
        });
    },

    beginMarkedContent: function (tag) {
        PDFOperator.of(Ops.BeginMarkedContent, [asPDFName(tag)]);
    },

    endMarkedContent: function () {
        PDFOperator.of(Ops.EndMarkedContent);
    },

    textFieldAppearanceStream: function (font, size, lines, x, y, width, height) {
        const dict = font.doc.context.obj({
            Type: 'XObject',
            Subtype: 'Form',
            FormType: 1,
            BBox: [0, 0, width, height],
            Resources: { Font: { F0: font.ref } },
        });

        const operators = [
            this.beginMarkedContent('Tx'),
            pushGraphicsState(),
            ...drawLinesOfText(lines, {
                color: rgb(1, 0, 0),
                font: 'F0',
                size: size,
                rotate: degrees(0),
                xSkew: degrees(0),
                ySkew: degrees(0),
                x: x,
                y: y,
                lineHeight: size + 2,
            }),
            popGraphicsState(),
            this.endMarkedContent(),
        ];

        const stream = PDFContentStream.of(dict, operators);
        return font.doc.context.register(stream);
    },

    singleLineAppearanceStream: function (font, text, width, height) {
        const size = font.sizeAtHeight(height - 5);
        const lines = [font.encodeText(text)];
        const x = 0;
        const y = height - size;
        return this.textFieldAppearanceStream(font, size, lines, x, y, width, height);
    },

    multiLineAppearanceStream: function (font, text, width, height) {
        const size = 12;
        const textWidth = t => font.widthOfTextAtSize(t, size);
        const lines = breakTextIntoLines(text, [' '], width, textWidth).map(line =>
            font.encodeText(line),
        );
        const x = 0;
        const y = height - size;
        return this.textFieldAppearanceStream(font, size, lines, x, y, width, height);
    },

    fillAcroTextField: function (acroField, text, font, multiline = false) {
        const rect = acroField.lookup(PDFName.of('Rect'), PDFArray);
        const width = rect.lookup(2, PDFNumber).value() - rect.lookup(0, PDFNumber).value();
        const height = rect.lookup(3, PDFNumber).value() - rect.lookup(1, PDFNumber).value();
        const N = multiline ? this.multiLineAppearanceStream(font, text, width, height) : this.singleLineAppearanceStream(font, text, width, height);

        acroField.set(PDFName.of('AP'), acroField.context.obj({ N }));
        acroField.set(PDFName.of('Ff'), PDFNumber.of(1 /* Read Only */));
        acroField.set(PDFName.of('V'), PDFHexString.fromText(text));
    },

    fillInField: function (pdfDoc, fieldName, text, font, multiline = false) {
        const field = this.findAcroFieldByName(pdfDoc, fieldName);
        if (!field) {
            throw new Error(`Missing AcroField: ${fieldName}`);
        }
        let isMultiline = text.indexOf("\r") > -1 || text.indexOf("\n") > -1;
        this.fillAcroTextField(field, text, font, isMultiline || multiline);
    },

    lockField: function (acroField) {
        acroField.set(PDFName.of('Ff'), PDFNumber.of(1 << 0 /* Read Only */));
    }
};

module.exports = pdfhelper;
```

And call it like that:

```
       const pdfDoc = await PDFDocument.load(fs.readFileSync('./assets/pdfs/File.pdf'));
        pdfDoc.registerFontkit(fontkit);
        const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
        const acroForm = pdfhelper.getAcroForm(pdfDoc);
        acroForm.set(PDFName.of('NeedAppearances'), PDFBool.True);
        pdfhelper.fillInField(pdfDoc, 'Company', 'Example Inc.', timesRomanFont);

        const acroFields = pdfhelper.getAcroFields(pdfDoc);
        acroFields.forEach(field => pdfhelper.lockField(field));

        const pdfBytes = await pdfDoc.save();

```

Any idea what's wrong?
Thanks for your help!

**Comment by alex90badea** [comment]
How did you fix?

**Comment by rajavijayavendan** [comment]
@Werewolve Any possible solution for this issue?

**Comment by eezz4** [comment]
If you use small quotes for Headings (##) content, that message will occur.
