### ISSUE TITLE
Trying to parse invalid object...

### ISSUE THREAD

**Issue by Brian-McBride** [Hopding/pdf-lib#523]
I have a PDF (real estate form) that I am trying to pull into the lib.
[PDF Form Link](https://drive.google.com/file/d/1Q04LEPpl6C9ytnQutyRJ4jG8dxOnpUTs/view?usp=sharing)

```
    Trying to parse invalid object: {"line":144,"column":16,"offset":2279078})

      at PDFParser.tryToParseInvalidIndirectObject (node_modules/pdf-lib/src/core/parser/PDFParser.ts:185:13)
      at PDFParser.<anonymous> (node_modules/pdf-lib/src/core/parser/PDFParser.ts:224:14)
      at step (node_modules/tslib/tslib.js:141:27)
      at Object.throw (node_modules/tslib/tslib.js:122:57)
      at rejected (node_modules/tslib/tslib.js:113:69)
```

The final error, after a few of ones similar to above has this:

```
    Invalid object ref: 22 0 R

      at PDFParser.tryToParseInvalidIndirectObject (node_modules/pdf-lib/src/core/parser/PDFParser.ts:189:13)
      at PDFParser.<anonymous> (node_modules/pdf-lib/src/core/parser/PDFParser.ts:224:14)
      at step (node_modules/tslib/tslib.js:141:27)
      at Object.throw (node_modules/tslib/tslib.js:122:57)
      at rejected (node_modules/tslib/tslib.js:113:69)
```

Since I'm here, thank you for making a lib that imports PDFs and supports Typescript. Love it.

**Comment by Hopding** [comment]
Hello @Brian-McBride! I just tried loading the document you shared with `PDFDocument.load`. Looks like the same issue as what was encountered in https://github.com/Hopding/pdf-lib/issues/369#issuecomment-614947505. pdf-lib does not currently support encrypted documents. There is a feature request for this though: https://github.com/Hopding/pdf-lib/issues/233.
