### ISSUE TITLE
PDF Parsing Issue

### ISSUE THREAD

**Issue by KateFontecilla** [Hopding/pdf-lib#559]
Hi,
I've been using pdf-lib since last year and it really helps me with my work. Lately, i've been encountering this issue  after embedding images in the PDF(with 29 pages) and this error appears: 

Trying to parse invalid object: {"line":1056,"column":6,"offset":186173})
Invalid object ref: 755 0 R

And when i tried getting the total page of that PDF, it returns 25 only which should be 29.
I also tried using the original pdf to see if i'll encounter that same issue, but everything works properly.

I am wondering if you could help me with this one. Thanks

**Comment by Hopding** [comment]
Hello @KateFontecilla!

Can you please share some PDFs and sample code that I can use to reproduce this issue?

**Comment by KateFontecilla** [comment]
Thanks for your immediate response. I only encountered that issue in one
PDF, and I'm sorry because I can't share that document 'cause it's
confidential but I can share you a sample code.
[image: image.png]

I am using that to convert the PDF into an arrayBuffer, then i use
PDFDocument.load(pdfBuffer)

**Comment by KateFontecilla** [comment]
[image: image.png]

Hi, I also looked into your code and I think it goes in this script. Hope
it helps.

**Comment by acoyfellow** [comment]
@Hopding here is a PDF I just ran into that has a bunch of errors while loading:

http://www.forms.ssb.gov.on.ca/mbs/ssb/forms/ssbforms.nsf/GetFileAttach/013-1572~1/$File/1572.pdf

Looking into what i can do about it now, and I came across this thread.

**Comment by Hopding** [comment]
```
Trying to parse invalid object: {"line":80,"column":16,"offset":12544})
Invalid object ref: 1324 0 R
Trying to parse invalid object: {"line":152,"column":16,"offset":157187})
Invalid object ref: 3 0 R
Trying to parse invalid object: {"line":160,"column":16,"offset":164738})
Invalid object ref: 6 0 R
Trying to parse invalid object: {"line":170,"column":16,"offset":169684})
Invalid object ref: 10 0 R
Trying to parse invalid object: {"line":456,"column":16,"offset":210391})
Invalid object ref: 148 0 R
Trying to parse invalid object: {"line":518,"column":16,"offset":215195})
Invalid object ref: 149 0 R
Trying to parse invalid object: {"line":560,"column":16,"offset":1734034})
Invalid object ref: 164 0 R
Trying to parse invalid object: {"line":582,"column":16,"offset":1735926})
Invalid object ref: 165 0 R
Trying to parse invalid object: {"line":606,"column":16,"offset":1738793})
Invalid object ref: 166 0 R
Trying to parse invalid object: {"line":630,"column":16,"offset":1741085})
Invalid object ref: 167 0 R
Trying to parse invalid object: {"line":642,"column":16,"offset":1742353})
Invalid object ref: 168 0 R
Trying to parse invalid object: {"line":668,"column":16,"offset":1743781})
Invalid object ref: 169 0 R
Trying to parse invalid object: {"line":680,"column":16,"offset":1745065})
Invalid object ref: 170 0 R
Trying to parse invalid object: {"line":692,"column":16,"offset":1746381})
Invalid object ref: 171 0 R
Trying to parse invalid object: {"line":708,"column":16,"offset":1747761})
Invalid object ref: 172 0 R
Trying to parse invalid object: {"line":726,"column":16,"offset":1749541})
Invalid object ref: 173 0 R
Trying to parse invalid object: {"line":740,"column":16,"offset":1750873})
Invalid object ref: 174 0 R
Trying to parse invalid object: {"line":758,"column":16,"offset":1756346})
Invalid object ref: 176 0 R
Trying to parse invalid object: {"line":764,"column":16,"offset":1756520})
Invalid object ref: 177 0 R
(node:83908) UnhandledPromiseRejectionWarning: Error: Input document to `PDFDocument.load` is encrypted. You can use `PDFDocument.load(..., { ignoreEncryption: true })` if you wish to load the document anyways.
    at new EncryptedPDFError (/Users/user/github/pdf-lib/scratchpad/build/src/api/errors.js:12:24)
    at new PDFDocument (/Users/user/github/pdf-lib/scratchpad/build/src/api/PDFDocument.js:58:19)
    at Function.<anonymous> (/Users/user/github/pdf-lib/scratchpad/build/src/api/PDFDocument.js:130:47)
    at step (/Users/user/github/pdf-lib/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/user/github/pdf-lib/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/Users/user/github/pdf-lib/node_modules/tslib/tslib.js:110:62)
```

@acoyfellow the document you shared is encrypted. `pdf-lib` does not currently support encrypted documents. It is on the roadmap though: https://github.com/Hopding/pdf-lib/discussions/998.
