### ISSUE TITLE
drawSvgPath circle fill error when using certain rrggbb values

### ISSUE THREAD

**Issue by dpkirchner** [Hopding/pdf-lib#773]
I can't seem to draw a specific SVG circle onto a PDF page (see below). ImageMagick can successfully convert the image to a PDF, although that doesn't necessarily mean it's absolutely correct (it seems to be right based on [Mozilla's SVG circle doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle)). I'm working against 1.15.0.

The following code works fine if I remove the circle's `fill` attribute, replace it with a string like `pink`, or replace it with a string like `#123456`(no letters).

```javascript
const {PDFDocument} = require('pdf-lib');

const main = async () => {
	const doc = await PDFDocument.create();
	const page = doc.addPage();

	page.drawSvgPath(`
<svg viewBox="0 0 72 72" xmlns="http://www.w3.org/2000/svg">
  <g id="color">
    <circle cx="36" cy="36" r="23" fill="#FCEA2B"/>
  </g>
</svg>
`);
};

main();
```

Output:

```bash
(node:74818) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.exports.numberToString (/Users/dpk/tmp/node_modules/pdf-lib/cjs/utils/numbers.js:28:30)
    at new PDFNumber (/Users/dpk/tmp/node_modules/pdf-lib/cjs/core/objects/PDFNumber.js:11:37)
    at Function.PDFNumber.of (/Users/dpk/tmp/node_modules/pdf-lib/cjs/core/objects/PDFNumber.js:34:46)
    at Object.exports.asPDFNumber (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/objects.js:9:69)
    at Object.exports.appendBezierCurve (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/operators.js:77:19)
    at Object.C (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/svgPath.js:154:28)
    at apply (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/svgPath.js:121:37)
    at Object.exports.svgPathToOperators (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/svgPath.js:379:55)
    at Object.exports.drawSvgPath (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/operations.js:199:18)
    at PDFPage.drawSvgPath (/Users/dpk/tmp/node_modules/pdf-lib/cjs/api/PDFPage.js:1009:62)
```

**Comment by dpkirchner** [comment]
You know what... I just realized this is taking an SVG *path* not the whole SVG document. Sorry, this is PEBKAC.
