### ISSUE TITLE
Using Custom font for Language Tamil Causes regeneratorRuntime is not defined Error

### ISSUE THREAD

**Issue by dsohscience37** [Hopding/pdf-lib#785]
When trying to use a custom font for the language Tamil and using setText on a text field, I'm getting an error on:

```
form.updateFieldAppearances(notoFont);
```

the weird thing is if i put an english character before the text eg:
'aஈஊ'

then it seems to work without issue.

tested with text:
'ஈஊ'

Tested with fonts: Google Noto Tamil and Catamaran

I've also tested with Arabic, Chinese, Japanese, Korean and Hebrew which seem to be working fine.

Below is the issue reported:

```
ReferenceError: regeneratorRuntime is not defined
    at StateMachine.match (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:35623:61)
    at setupSyllables (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:35996:72)
    at ShapingPlan.process (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:34378:12)
    at OTLayoutEngine.substitute (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:37883:18)
    at LayoutEngine.substitute (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:38029:20)
    at LayoutEngine.layout (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:38015:11)
    at TTFFont.layout (/usr/src/app/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:41414:32)
    at CustomFontEmbedder.widthOfTextAtSize (/usr/src/app/node_modules/pdf-lib/cjs/core/embedders/CustomFontEmbedder.js:62:32)
    at PDFFont.widthOfTextAtSize (/usr/src/app/node_modules/pdf-lib/cjs/api/PDFFont.js:53:30)
    at computeFontSize (/usr/src/app/node_modules/pdf-lib/cjs/api/text/layout.js:14:32)
```

**Comment by dsohscience37** [comment]
Seem to be able to get the same error by running

```
    const notoFont = await pdfDoc.embedFont(fontBytes);
    console.log('here we go');
    console.log(notoFont.encodeText('ஈஊ'));
```

but it works fine if i do 

```
    const notoFont = await pdfDoc.embedFont(fontBytes);
    console.log('here we go');
    console.log(notoFont.encodeText('aஈஊ'));

```

**Comment by dsohscience37** [comment]
it doesnt seem like it has to be english character before even korean and chinese work just seems to be something wrong with tamil
```
 const notoFont = await pdfDoc.embedFont(fontBytes);
    console.log(notoFont.encodeText('라ஈஊ')); // korean works
```

**Comment by aslampr07** [comment]
I have the same issue with Malayalam,  did you fix it?

**Comment by dsohscience37** [comment]
No however what i noticed is some characters dont crash, so i made a loop that goes through each char number 1 through 65505 and made it print out in the font of my choosing. i found a character that works in a range that people wont use, then i used a font editor and made it a blank character. so now im injecting a blank character before if it is using tamil.

I would still like this addressed since this is a temporary fix until @Hopding can look into it, but hopefully this helps you until this is resolved.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
