### ISSUE TITLE
How to use pdf-lib with nw.js if I want to build a desktop application?

### ISSUE THREAD

**Issue by catchmyhand** [Hopding/pdf-lib#787]
Hey, guys!
I have used the sample codes with node.js to combine two pdf files into one pdf file( with hard-code the input/output file names). It can be running in VSCode env or command line. When I use nw.js to generate a page which user can choose the input files and output file name/path, it prompt me with error message like that:

TypeError: `indices` must be of type `Array`, but was actually of type `Array`
    at Object.exports.assertIs (E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at PDFDocument.<anonymous> (E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\pdf-lib\cjs\api\PDFDocument.js:643:33)
    at step (E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\tslib\tslib.js:141:27)
    at Object.next (E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\tslib\tslib.js:122:57)
    at E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\tslib\tslib.js:111:16)
    at PDFDocument.copyPages (E:\nwjsv0.51.0\UserApps\pdfcbm\node_modules\pdf-lib\cjs\api\PDFDocument.js:637:24)
    at run (chrome-extension://kkfeahkblghiflgnkimghlephfcelgkl/index.html:24:39)

my codes is below:(two form input element with type="file")
      function merge_pdf() {
        var pdf1 = document.file_form.pdf1.value;
        var pdf2 = document.file_form.pdf2.value;

        var fs = require('fs');
        var { PDFDocument } = require('pdf-lib');

        run().catch(err => console.log(err));
        async function run() {
          // Load cover and content pdfs
          var cover = await PDFDocument.load(fs.readFileSync(pdf1));
          var content = await PDFDocument.load(fs.readFileSync(pdf2));

          // Create a new document
          var doc = await PDFDocument.create();

          // Add the cover to the new doc
          var [coverPage] = await doc.copyPages(cover, [0]);
          doc.addPage(coverPage);

          // Add individual content pages
          var contentPages = await doc.copyPages(content, content.getPageIndices());
          for (var page of contentPages) {
            doc.addPage(page);
          }

          // Write the PDF to a file
          fs.writeFileSync('./newinv.pdf', await doc.save());
          console.log('Done');
        }
      }

Can anyone get idea about this?

Thanks a lot!

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
