### ISSUE TITLE
TypeError: `font` must be of type `PDFFont` or `n`, but was actually of type `NaN`

### ISSUE THREAD

**Issue by AlanaziNaif** [Hopding/pdf-lib#842]
```
const { PDFDocument, StandardFonts } = require("pdf-lib");
const path = require("path");
const fs = require("fs");
const fontkit = require("@pdf-lib/fontkit");

async function fillForm() {
  // Fetch the PDF with form fields
  const pdfFilepath = path.join(__dirname, "/pdftemp/salary.pdf");
  const uint8Array = fs.readFileSync(pdfFilepath);
  // Fetch the font
  const fontpath = path.join(__dirname, "/fonts/Cairo/Ubuntu-R.ttf");
  const uint8ArrayFont = fs.readFileSync(fontpath);
  // Load the PDF with form fields
  const pdfDoc = PDFDocument.load(uint8Array);
  // Embed the font
  (await pdfDoc).registerFontkit(fontkit);
  const embedfont = (await pdfDoc).embedFont(uint8ArrayFont);
  const emb = embedfont.then((i) => console.log(i));
  // Get text fields from the form
  const form = (await pdfDoc).getForm();
  const name = form.getTextField("name");
  const nationality = form.getTextField("nationality");
  const id = form.getTextField("id");
  const jobTitle = form.getTextField("jobTitle");
  const JoiningDate = form.getTextField("JoiningDate");
  const SR = form.getTextField("SR");
  const arabicName = form.getTextField("arabicName");

  // Fill the text fields
  name.setText("name name naem");
  nationality.setText("Nationality");
  id.setText("1038992853");
  jobTitle.setText("HR Officer");
  JoiningDate.setText("27/2/2021");
  SR.setText("5452");
  arabicName.setText("خط عربي");

  // **Key Step:** Update the field appearances with the Ubuntu font
  form.updateFieldAppearances(embedfont);

  // Save the PDF with filled form fields

  const pdfBytes = (await pdfDoc).save().then((item) => {
    const newpdfFilepath = path.join(__dirname, "/pdftemp/test1.pdf");
    fs.writeFileSync(newpdfFilepath, item);
  });
}

fillForm();
```

```
Console.log... 
$ node index.js 
<ref *1> PDFFont {
  modified: true,
  ref: PDFRef { objectNumber: 165, generationNumber: 0, tag: '165 0 R' },
  doc: PDFDocument {
    defaultWordBreaks: [ ' ' ],
    computePages: [Function (anonymous)],
    getOrCreateForm: [Function (anonymous)],
    context: PDFContext {
      largestObjectNumber: 165,
      header: [PDFHeader],
      trailerInfo: [Object],
      indirectObjects: [Map]
    },
    catalog: PDFCatalog { dict: [Map], context: [PDFContext] },
    isEncrypted: false,
    pageCache: Cache { populate: [Function (anonymous)], value: undefined },
    pageMap: Map(0) {},
    formCache: Cache { populate: [Function (anonymous)], value: [PDFForm] },
    fonts: [ [Circular *1] ],
    images: [],
    embeddedPages: [],
    embeddedFiles: [],
    javaScripts: [],
    fontkit: {
      logErrors: false,
      registerFormat: [Function: registerFormat],
      create: [Function: create]
    }
  },
  name: 'Cairo-Regular',
  embedder: CustomFontEmbedder {
    allGlyphsInFontSortedById: [Function (anonymous)],
    font: TTFFont {
      stream: [DecodeStream],
      variationCoords: null,
      _directoryPos: 0,
      _tables: [Object],
      _glyphs: {},
      directory: [Object]
    },
    scale: 1,
    fontData: <Buffer 00 01 00 00 00 11 01 00 00 04 00 10 47 44 45 46 5b 2e 83 09 00 01 d6 68 00 00 02 68 47 50 4f 53 55 cb 5b cf 00 01 d8 
d0 00 00 67 f4 47 53 55 42 7b f0 ... 151554 more bytes>,
    fontName: 'Cairo-Regular',
    customName: undefined,
    fontFeatures: undefined,
    baseFontName: '',
    glyphCache: Cache { populate: [Function (anonymous)], value: undefined }
  }
}
C:\Users\naifc\Desktop\script\cppForm\node_modules\pdf-lib\cjs\utils\validators.js:140
    throw new TypeError(exports.createTypeErrorMsg(value, valueName, types));
          ^

TypeError: `font` must be of type `PDFFont` or `n`, but was actually of type `NaN`
    at Object.exports.assertIs (C:\Users\naifc\Desktop\script\cppForm\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at Object.exports.assertOrUndefined (C:\Users\naifc\Desktop\script\cppForm\node_modules\pdf-lib\cjs\utils\validators.js:143:13)        
    at PDFForm.updateFieldAppearances (C:\Users\naifc\Desktop\script\cppForm\node_modules\pdf-lib\cjs\api\form\PDFForm.js:529:17)
    at fillForm (C:\Users\naifc\Desktop\script\cppForm\index.js:43:8)

naifc@DESKTOP-N4D7CN0 MINGW64 ~/Desktop/script/cppForm
$ node index.js 
C:\Users\naifc\Desktop\script\cppForm\node_modules\@pdf-lib\standard-fonts\lib\Encoding.js:23
                throw new Error(msg);
                      ^

Error: WinAnsi cannot encode "خ" (0x062e)
    at Encoding.encodeUnicodeCodePoint (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4m@pdf-lib←[24m\standard-fonts\lib\Encoding.js:23:23)
    at StandardFontEmbedder.encodeTextAsGlyphs (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\core\embedders\StandardFontEmbedder.js:88:41)
    at StandardFontEmbedder.widthOfTextAtSize (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\core\embedders\StandardFontEmbedder.js:36:27)
    at PDFFont.widthOfTextAtSize (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\PDFFont.js:53:30)
    at computeFontSize (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\text\layout.js:14:32)
    at Object.exports.layoutSinglelineText (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\text\layout.js:182:20)
    at exports.defaultTextFieldAppearanceProvider (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\form\appearances.js:260:31)
    at PDFTextField.updateWidgetAppearance (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\form\PDFTextField.js:718:61)
    at PDFTextField.updateAppearances (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\form\PDFTextField.js:712:18)
    at PDFTextField.defaultUpdateAppearances (C:\Users\naifc\Desktop\script\cppForm\node_modules\←[4mpdf-lib←[24m\cjs\api\form\PDFTextField.js:688:14)

naifc@DESKTOP-N4D7CN0 MINGW64 ~/Desktop/script/cppForm
$ node index.js 
<ref *1> PDFFont {
  modified: true,
  ref: PDFRef { objectNumber: 165, generationNumber: 0, tag: '165 0 R' },
  doc: PDFDocument {
    defaultWordBreaks: [ ' ' ],
    computePages: [Function (anonymous)],
    getOrCreateForm: [Function (anonymous)],
    context: PDFContext {
      largestObjectNumber: 165,
      header: [PDFHeader],
      trailerInfo: [Object],
      indirectObjects: [Map]
    },
    catalog: PDFCatalog { dict: [Map], context: [PDFContext] },
    isEncrypted: false,
    pageCache: Cache { populate: [Function (anonymous)], value: undefined },
    pageMap: Map(0) {},
    formCache: Cache { populate: [Function (anonymous)], value: [PDFForm] },
    fonts: [ [Circular *1] ],
    images: [],
    embeddedPages: [],
    embeddedFiles: [],
    javaScripts: [],
    fontkit: {
      logErrors: false,
      registerFormat: [Function: registerFormat],
      create: [Function: create]
    }
  },
  name: 'Cairo-Regular',
  embedder: CustomFontEmbedder {
    allGlyphsInFontSortedById: [Function (anonymous)],
    font: TTFFont {
      stream: [DecodeStream],
      variationCoords: null,
      _directoryPos: 0,
      _tables: [Object],
      _glyphs: {},
      directory: [Object]
    },
    scale: 1,
    fontData: <Buffer 00 01 00 00 00 11 01 00 00 04 00 10 47 44 45 46 5b 2e 83 09 00 01 d6 68 00 00 02 68 47 50 4f 53 55 cb 5b cf 00 01 d8 
d0 00 00 67 f4 47 53 55 42 7b f0 ... 151554 more bytes>,
    fontName: 'Cairo-Regular',
    customName: undefined,
    fontFeatures: undefined,
    baseFontName: '',
    glyphCache: Cache { populate: [Function (anonymous)], value: undefined }
  }
}
\node_modules\pdf-lib\cjs\utils\validators.js:140
    throw new TypeError(exports.createTypeErrorMsg(value, valueName, types));
          ^

TypeError: `font` must be of type `PDFFont` or `n`, but was actually of type `NaN`
    at Object.exports.assertIs (\node_modules\pdf-lib\cjs\utils\validators.js:140:11)
    at Object.exports.assertOrUndefined (\node_modules\pdf-lib\cjs\utils\validators.js:143:13)        
    at PDFForm.updateFieldAppearances (\node_modules\pdf-lib\cjs\api\form\PDFForm.js:529:17)
    at fillForm (\index.js:39:8)

```

Could anyone help?

**Comment by StefanZivkovic** [comment]
```
pdfDoc.registerFontkit(fontkit);
const fontBytes = fs.readFileSync(path.join(__dirname, `/fonts/${font}.otf`));
const pdfFont = await pdfDoc.embedFont(fontBytes);

const form = pdfDoc.getForm();
const textField = form.getTextField(fieldName);
textField.updateAppearances(pdfFont);
```

This is my working solution with `pdf-lib1.16.0`. I see you are trying to apply font to whole form (not sure how is that suppose to behave). I did it on single textField.
