### ISSUE TITLE
Using a .ttc file for a font with subset

### ISSUE THREAD

**Issue by dreignier** [Hopding/pdf-lib#944]
I'm having issue when I try to use a .ttc file for a font with `subset: true`.
pdf-lib produces an error with an error message : `this.font.layout is undefined`

After some dig in the code, it appears pdf-lib doesn't handle .ttc file at all. `CustomFontSubsetEmbedder.for` doesn't handle a `postscriptName`.

I can modify `CustomFontSubsetEmbedder.for` to handle a .ttc file, like this:

```
CustomFontSubsetEmbedder.for = async function(fontkit, fontData, customName, fontFeatures) {
    let font = fontkit.create(fontData, 'myPostscriptName');
    return new CustomFontEmbedder(font, fontData, customName, fontFeatures);
}
```

But after doing, when I try to save the pdf document, I got this error:

```
RangeError: "value" argument is out of bounds
    at checkInt (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:1530:44)
    at Uint8Array.writeUInt8 (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:1579:21)
    at EncodeStream.<computed> [as writeUInt8] (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:16286:32)
    at NumberT.encode (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:16453:42)
    at Struct.encode (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:17331:19)
    at RangeArray.ArrayT.encode (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:16695:22)
    at VersionedStruct.encode (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:17532:19)
    at VersionedStruct.encode (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:17540:21)
    at CFFSubset.encode (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:41198:13)
    at /home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:40692:14
    at Item.run (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:2632:13)
    at Timeout.drainQueue (/home/foo/sources/foo/node_modules/@pdf-lib/fontkit/dist/fontkit.umd.js:2597:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Is there any way to use a .ttc file for a font when you want to create a subset of this font ?

**Comment by dreignier** [comment]
More informations. The issue seems to come from fontkit. The font I try to use has a `CFF ` table and fontkit uses another class for this specific case. This class (`CFFSubset`) doesn't seems to work.

**Comment by Hopding** [comment]
Subsetting is not well supported right now. See https://github.com/Hopding/pdf-lib/issues/494#issuecomment-695818400.

I've added this to the roadmap for tracking as it's something I'd like to offer better support for: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by matt2023y** [comment]
https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/core/embedders/CustomFontEmbedder.ts#L28 
Maybe  adds a parameter named postscriptName to pass in fontkit.create function when using ttc?
