### ISSUE TITLE
Unexpected N type: undefined

### ISSUE THREAD

**Issue by Newbie012** [Hopding/pdf-lib#952]
Given the following file - [cms 1500 claim form.pdf](https://github.com/Hopding/pdf-lib/files/6924025/cms.1500.claim.form.pdf)

And the following code:

```ts
import { PDFDocument } from "pdf-lib"

const buffer = ... // the buffer of the PDF above

const pdfDoc = await PDFDocument.load(buffer)

const form = pdfDoc.getForm()

form.flatten()
```

Getting this error:

```
{
    "errorMessage": "Unexpected N type: undefined",
    "errorType": "Error",
    "stackTrace": [
        "Error: Unexpected N type: undefined",
        "    at PDFWidgetAnnotation.PDFAnnotation.getNormalAppearance (/home/eliya/projects/medflyt-serverless/node_modules/pdf-lib/src/core/annotation/PDFAnnotation.ts:70:11)",
        "    at PDFForm.findWidgetAppearanceRef (/home/eliya/projects/medflyt-serverless/node_modules/pdf-lib/src/api/form/PDFForm.ts:718:28)",
        "    at PDFForm.flatten (/home/eliya/projects/medflyt-serverless/node_modules/pdf-lib/src/api/form/PDFForm.ts:551:32)",
        "    at /home/eliya/projects/medflyt-serverless/src/lambdas/fillPdf/fillPdf.ts:33:10",
        "    at interceptHandler (/home/eliya/projects/medflyt-serverless/src/actions/interceptHandler.ts:5:18)"
    ]
}
```

**Comment by Newbie012** [comment]
I had to transfer the pdf from PDF to PDF/A

**Comment by sepsol** [comment]
@Newbie012 How did you do that?
